### ISSUE TITLE
Introduction not above the fold

### ISSUE THREAD

**Issue by metbril** [EmielH/hallo-hugo#18]
Using an older MacBook Air with screen resolution, the Introduction page, including the social icons, does not get fitted into the first full page. Part of my introduction text is cut off, and the social icons are not on the first screen. I have to scroll to see them.

The resolution is 1440x900 pixels.

There is sufficient room above my portrait to fit it.

**Comment by EmielH** [comment]
Thanks for bringing this to my attention! I will look into this as soon as I have a bit of spare time.

**Comment by msuiche** [comment]
Agreed. This is what I see
![image](https://user-images.githubusercontent.com/1621145/70860485-8e00fd00-1f22-11ea-9f70-b4ec66090e51.png)

Here is my resolution:
![image](https://user-images.githubusercontent.com/1621145/70860498-ad982580-1f22-11ea-8b5c-45c7897c8927.png)

**Comment by EmielH** [comment]
@metbril @msuiche Could you tell me the browsers that you're using? I'm having a hard time reproducing this behaviour.

**Comment by metbril** [comment]
Mostly Firefox (Mac) but  I think the same goes for Brave and Safari for Mac. I will check when I have access to a computer.

**Comment by Sidra-Kazmi** [comment]
Hello, I am seeing the distorted page layout as well. I tried this on 3 browsers. Chrome, Opera and Edge. The Zoom resolution on the browsers is set to 125% and my display resolution is 
![image](https://user-images.githubusercontent.com/69394495/90268950-706f9480-de1d-11ea-9a82-e0d09435d2f4.png).

**Comment by EmielH** [comment]
Thanks for letting me know! I will investigate again.

**Comment by metalolf** [comment]
Same here!

**Comment by vale-tech** [comment]
Yeah same problem for me as well. The sample site at https://themes.gohugo.io/theme/hallo-hugo/ looks fine though which is a bit strange.

**Comment by EmielH** [comment]
These are interesting clues. I will test with the regular version of Hugo. Does any of you have your site in a public repo so I can check that too?

**Comment by metbril** [comment]
I haven't checked it for a while but this is my repo:

https://github.com/metbril/hallo-robert

**Comment by vale-tech** [comment]
https://github.com/vale-tech/vtrujillo-website

Your theme was exactly what I was looking for. Thanks!

**Comment by EmielH** [comment]
Thanks to your tips I think I finally found the cause of this issue. It looks like some styles were missing from the pre-generated CSS files for Hugo Basic. I just committed a patch. Could you check if this solves your problem?

**Comment by vale-tech** [comment]
Yes sir, working now for me with normal Hugo and Win10. Cheers!

**Comment by EmielH** [comment]
Glad to hear it! I'll close this issue and release a new version.

**Comment by metbril** [comment]
It's not yet fixed for me:

<img width="1440" alt="afbeelding" src="https://user-images.githubusercontent.com/559346/99564962-5ff62980-29cb-11eb-94b8-09af0d5ad9be.png">

**Comment by EmielH** [comment]
Ah! That's actually a different issue (probably the one you tried to report in the first place). My apologies for misunderstanding. I was going by the screenshots earlier in this issue. Currently, the spacing between the different parts of the site (e.g. the space above the photo and the space between the headers) is fixed. I created a new issue (#22) to try and improve this.
